feat(lifetime): add customisable expiration dates
subshell/o-neko pull request #65
Opened 2021-11-09 10:14 UTC by tom-schoener

2021-11-11 14:20 UTC, philmtd reviewed
Generally this looks good to me, I only left a small comment in the code.

Reading the code made me think whether the configuration like this is the best we can get. The issues I have are:
- via the day-offset is possible to create crazy configurations stopping deployments after any amount of time - even months/years/millenias
- when the day-offset is set to say.. 5 and lastDayOfWeek is "friday", then the "next weekend" setting would result in deployments being stopped on wednesday.

Do you think we can find a configuration that is not prone to these misconfiguration options?

2021-11-11 14:21 UTC, philmtd requested changes
Changes requested due to my previous comment.

2021-11-12 16:34 UTC, tom-schoener commented on src/main/java/io/oneko/automations/LifetimeProperties.java
> +	private String lastDayOfTheWeek;
We decided to keep the current `lastDayOfTheWeek` configuration.

2021-11-16 11:56 UTC, philmtd approved these changes

2021-11-16 11:56 UTC, merged