Sleep for 10s between "helm uninstall" and "helm install"
subshell/o-neko pull request #89
Opened 2022-09-01 10:39 UTC by muffl0n

2022-09-01 15:17 UTC, philmtd requested changes
I'm not fully convinced yet that this is the best solution for the problem.

As far as I see what we want to achieve is: The uninstallation needs to be completed before we install the application again.

We provide our own Helm API wrapper in the `helmapi` package. Do you think we could add the `--wait` parameter of `helm delete` (and other commands that offer it) optionally and exposed through a method parameter, so we let Helm wait until all resources are deleted? Could this work?

2022-09-01 15:17 UTC, philmtd commented on src/main/java/io/oneko/kubernetes/impl/DeploymentManagerImpl.java
> +				Thread.sleep(10000);
Won't this also block the HTTP request sent by the frontend?

And shouldn't this be in the block above, so it's only executed when an application is actually uninstalled?

2022-09-01 16:06 UTC, muffl0n commented
>  ... so we let Helm wait until all resources are deleted? Could this work?

Sounds good! I thought that this was already done. I'm expecting a race condition between the deletion of the ingress, the ingress controller reacting to it and the creation of the new ingress.
So waiting explicitly for the deletion sounds like a wise idea.

2022-09-02 06:57 UTC, muffl0n commented
Added `--wait` to `helm uninstall`. Didn't make it optional, cause there is no sense in not waiting, imho.

2022-09-02 13:21 UTC, philmtd commented
I'd like to have the `--wait` argument optionally on both the `uninstall` and `install` methods. That way we could prevent HTTP calls coming from the API to have to wait for the uninstallation to finish. Waiting is not required either when the scheduled shutdown is configured. We literally only require to wait when we immediately after that plan to install again. So I'd really love to have that argument and to be able to pass it optionally (default should be `false`).

2022-09-07 13:32 UTC, philmtd reviewed
I made the change I wanted. Could you review this please @muffl0n?

2022-09-07 14:30 UTC, muffl0n commented
LGTM! I can't approve cause it's my PR. :)

2022-09-09 11:18 UTC, philmtd approved these changes

2022-09-09 13:19 UTC, merged